export const CONNECTION_STATE = Object.freeze({
  NC03_FOUND: "NC03_FOUND",
  NC03_UNAVAILABLE: "NC03_UNAVAILABLE",
  CONNECTED: "CONNECTED",
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  RECONNECTING: "RECONNECTING",
  UNSUPPORTED_FIRMWARE: "UNSUPPORTED_FIRMWARE"
});

const LABELS = Object.freeze({
  [CONNECTION_STATE.NC03_FOUND]: "NC03 found",
  [CONNECTION_STATE.NC03_UNAVAILABLE]: "NC03 unavailable",
  [CONNECTION_STATE.CONNECTED]: "Connected",
  [CONNECTION_STATE.AUTHENTICATION_REQUIRED]: "Authentication required",
  [CONNECTION_STATE.WRONG_PASSWORD]: "Wrong password",
  [CONNECTION_STATE.SESSION_EXPIRED]: "Session expired",
  [CONNECTION_STATE.RECONNECTING]: "Reconnecting",
  [CONNECTION_STATE.UNSUPPORTED_FIRMWARE]: "Unsupported firmware"
});

export function connectionStateLabel(state) {
  return LABELS[state] ?? "NC03 unavailable";
}
